export { default as Head} from './Head'
export { default as Nav} from './Nav'
export { default as NewsList} from './NewsList'
export { default as Loading} from './Loading'
export { default as Slider} from './Slider'
export { default as NewsListView} from './NewsListView'
