export { default as App} from './App'
export { default as Home} from './Home'
export { default as Film} from './Film'
export { default as Cinema} from './Cinema'
export { default as User} from './User'
export { default as Detail} from './Detail'
